apiVersion: v1
kind: Pod
metadata:
  name: terraform-runner
  namespace: monitoring
spec:
  containers:
  - name: terraform
    image: hashicorp/terraform:latest
    command: ['sleep', 'infinity']
    workingDir: /workspace
  restartPolicy: Never
